api/src/main/resources/application.yaml

Logging format update

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/struct/GradStudent.java

# WARNING: head commit changed in the meantime

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/CustomRequestBodyAdviceAdapter.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/GradCommonConfig.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/RequestInterceptor.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/RestWebClient.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/CommonController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/HistoryService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/LogHelper.java
api/src/main/resources/application.yaml
tools/openshift/api.dc.yaml

Splunk integration is implemented.

Splunk integration is applied.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/RequestInterceptor.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/RestWebClient.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/entity/BaseEntity.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/CommonService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GradStudentService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/HistoryService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/ThreadLocalStateUtil.java

username is saved in transaction & correlationID is logged into Splunk.

username is saved in transaction & correlationID is logged into Splunk.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/RequestInterceptor.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/JwtUtil.java

just name is used from JWT.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/main/resources/application.yaml
api/src/test/resources/application.yaml

GRAD2-1554: making ongoing updates optional.

GRAD2-1554: making ongoing updates optional.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/transformer/GraduationStatusTransformer.java

GRAD2-1593 Changes to Graduation Report GRADREG

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java

GRAD2-1625: bug fix

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/GraduationStatusController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/entity/GraduationStudentRecordSearchEntity.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordSearchRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordSearchSpecification.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusServiceTest.java

GRAD2-1670: the issue is resolved.

GRAD2-1670: the issue is resolved.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/StudentDemographic.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java

[GRAD2-1680](https://gww.jira.educ.gov.bc.ca/browse/GRAD2-1680)
Populate School Type Indicator in the Json for STS student demographic

GRAD2-1680

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java

GRAD2-1679: fixed the issue.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java

Student Demographics Json for STS needs an update

GRAD2-1689

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/GradSearchStudent.java

GRAD2-1683

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/StudentCareerProgramRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/StudentOptionalProgramRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusServiceTest.java

GRAD2-1754: bug fix

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiUtils.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusServiceTest.java

GRAD2-1240 : the task is completed

GRAD2-1240 : the task is completed

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiUtils.java

GRAD2-1240 : the task is complete

GRAD2-1240 : the task is complete

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/DataConversionController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/StudentCareerProgramRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/main/resources/application.yaml
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/DataConversionControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/GraduationStatusControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionServiceTest.java
api/src/test/resources/application.yaml

GRAD2-1888: task is complete

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/CommonController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/ReportGradStudentDataRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GradStudentReportService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/CommonControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/CommonServiceTest.java

Year-End Disribution run (DISTRUN_YE) - reports School-Level (DISTREP_YE_SC) and District-Level (DISTREP_YE_SD)

GRAD2-1850

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/DataConversionController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/StudentDemographic.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/StudentOptionalProgramRequestDTO.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/transformer/GradStudentOptionalProgramTransformer.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/transformer/GraduationStatusTransformer.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/DataConversionControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionServiceTest.java

GRAD2-1826: task is complete

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java

Bug fix on saving graduation student record as part of ongoing updates.

Bug fix on saving graduation student record as part of ongoing updates.

---

.github/workflows/build.from.main.branch.deploy.to.dev.yml
.github/workflows/build.from.release.branch.deploy.to.dev.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_test.yml
Dockerfile
tools/openshift/api.dc.yaml

Grad Student API resource optimization is done

GRAD2-1947 Resource optmization

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/RequestInterceptor.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/RestWebClient.java
api/src/main/resources/application.yaml
api/src/test/resources/application.yaml

Grad Student API refactoring/linting is done

GRAD2-1929 Refactoring/Linting

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/DataConversionController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/DataConversionControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionServiceTest.java

GRAD2-1966 : task is complete.

GRAD2-1966 : task is complete.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/entity/GraduationStudentRecordEntity.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordHistoryRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/StudentOptionalProgramHistoryRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/StudentOptionalProgramRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/scheduler/JetStreamEventScheduler.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java

GRAD2-2026: the deadlock issue is resolved.

GRAD2-2026: the deadlock issue is resolved.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionServiceTest.java

GRAD2-2026: the issue is fixed.

GRAD2-2026: the issue is fixed.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/DataConversionController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/DataConversionControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionServiceTest.java

GRAD2-2090: task is complete

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java

GRAD2-2199: task is completed to reset programCompletionDate when SCCP is changed to another grad program.

GRAD2-2199: task is complete

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/transformer/GraduationStudentRecordHistoryTransformer.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/DateUtils.java

GRAD2-2266: task is completed.

GRAD2-2266: task is completed.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java

Audit record now showing IDIR - User runs graduation algorithm from the student Grad status page and updates students' data

Grad2-1669 Audit record now showing IDIR

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/transformer/GraduationStatusTransformer.java

GRAD2-2139: task is completed.

GRAD2-2139: task is completed.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GradStudentService.java

GRAD2-2326: the deceased check query is enhanced to support paging.

GRAD2-2326: the deceased check query is enhanced to support paging.

---

api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/gradstudent/constant/Topics.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/messaging/jetstream/FetchGradStatusSubscriber.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/GradTraxStudent.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/scheduler/JetStreamEventScheduler.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/CommonService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GradStudentService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/main/resources/application.yaml
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/CommonServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/GradStudentServiceTest.java
api/src/test/resources/application.yaml

Grad Release 1.6.0

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java

GRAD2-2372: a P2 issue has been resolved.

GRAD2-2372: a P2 issue has been resolved.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/entity/BaseEntity.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/transformer/GraduationStatusTransformer.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/transformer/GraduationStudentRecordHistoryTransformer.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/CommonServiceTest.java

Updated date on Student GRAD Status page defaulting to today's date regardless of when student record has been last updated
UI: Optional Program History not showing correct date

GRAD2-2361,2360

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java

GRAD2-2362 & GRAD2-2388: task is complete.

GRAD2-2362 & GRAD2-2388: task is complete.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/constant/FieldName.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/constant/FieldType.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/constant/TraxEventType.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/DataConversionController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/OngoingUpdateFieldDTO.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/OngoingUpdateRequestDTO.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/DataConversionControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionServiceTest.java

GRAD2-2389, 2390, 2412: task is complete.

GRAD2-2389, 2390, 2412: task is complete.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java

Done with updating flags as per validations.

Grad2-2341 part-6 Setting the flags as per validations

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java

setting updated flags while program is changed.

Grad2-2341 part6 set updated flages when program is changed.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java

GRAD2-2431: task is completed.

GRAD2-2431: task is completed.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GradStatusEventRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/scheduler/PurgeOldRecordsScheduler.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/main/resources/application.yaml
api/src/test/resources/application.yaml

GRAD2-2430: task is completed.

GRAD2-2430: task is completed.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionServiceTest.java

GRAD2-2442: task is complete.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/GraduationStatusController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordHistoryRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/HistoryService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/GraduationStatusControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/HistoryServiceTest.java

Corrected the username when Archived student is edited..

Grad2-2434 Editing Archived students' record inserts the last processes user name

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/CommonController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/entity/StudentCareerProgramEntity.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/StudentCareerProgramRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/CommonControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusServiceTest.java

Backend changes for Optional Program CRUD

GRAD2-2464

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusServiceTest.java

Further Backend changes for Optional Program CRUD

GRAD2-2522

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/CommonController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/StudentCareerProgramRequestDTO.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/StudentCareerProgramRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/GradValidation.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/CommonControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/DataConversionControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/GraduationStatusControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/HistoryServiceTest.java

GRAD2-2522: task is completed.

GRAD2-2522: task is completed.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/CommonController.java

GRAD2-2522: clean up API docs for CRUD optional/career program.

GRAD2-2522: clean up API docs for CRUD optional/career program.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/StudentNoteRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java

GRAD2-2465 - Delete a student and related data

GRAD2-2465 - Delete a student and related data

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/GraduationStudentRecordDistribution.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/transformer/GraduationStatusTransformer.java

HD-22859 (GRAD) YE Distribution run should direct Certificates to School at Graduation, not School of Record

GRAD2-2377

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/main/resources/application.yaml
api/src/test/resources/application.yaml

Done with endpoint replacements

Grad2-2632 school api call is replaced with trax api.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordSearchSpecification.java

(GRAD) Fix User Request Distribution Run options - Part 2 - CUR and Null Distribution Dates

GRAD2-2580

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/GraduationStatusController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/GraduationStatusControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusServiceTest.java

P2 GRAD Incident: Not-Yet Graduated Report is Not Updated when ALL the students are graduated in the REGALG

GRAD2-2855

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/entity/BaseEntity.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/HistoryService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/HistoryServiceTest.java

Student Archive Process - Backend endpoints To COMPLETE

GRAD2-2283

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/StudentSearchRequest.java

User Distribution Run downloaded report files are empty

GRAD2-2958

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/HistoryService.java

Student Archive for one school needs to be able to handle > 1000 students

GRAD2-2971

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/constant/TraxEventType.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/GradSearchStudent.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/GraduationStudentRecord.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordHistoryRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionServiceTest.java

GRAD2-3019: task is complete.

---

.github/dependabot.yml
.github/workflows/build.from.developer.branch.deploy.to.dev.yml
.github/workflows/build.from.main.branch.deploy.to.dev.yml
.github/workflows/build.from.release.branch.deploy.to.dev.yml

Grad2-3132 ZAPscan version upgraded

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/constant/FieldName.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/GradStatusEventPayloadDTO.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/SchoolClob.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/main/resources/application.yaml
tools/config/update-configmap.sh

GRAD2-3220: task is completed.

GRAD2-3220: task is completed.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/GradStudentServiceTest.java

Grad2-3187 Certificates are now using school of graduation

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java

Retrieved mincode from school clob on schoolAtGradID condition

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiUtils.java

GRAD2-3220: Bug fix on getting null school id in the payload of ongoing update events from GRAD to TRAX.

 GRAD2-3220: Bug fix on null school id in the payload of ongoing update events from GRAD to TRAX.

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/constant/FieldName.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GradBaseService.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/DataConversionServiceTest.java

GRAD2-3169: task is complete.

---

.github/workflows/on.pr.yml
api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/RequestInterceptor.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/RestWebClient.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/CommonService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GradBaseService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GradStudentService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GraduationStatusService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/HistoryService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/JwtUtil.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/LogHelper.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/ThreadLocalStateUtil.java

Grad2-3284 Set Request Headers

---

api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/gradstudent/config/WebSecurityConfiguration.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/APIMetadataController.java

GRAD2-3335 - Add Metadata Endpoint to All GRAD APIs

GRAD2-3335 - Add Metadata Endpoint to All GRAD APIs

---

api/src/main/java/ca/bc/gov/educ/api/gradstudent/controller/GradStudentController.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/model/dto/GraduationCountProjection.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/repository/GraduationStudentRecordRepository.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/service/GradStudentService.java
api/src/main/java/ca/bc/gov/educ/api/gradstudent/util/EducGradStudentApiConstants.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/controller/GradStudentControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/gradstudent/service/GradStudentServiceTest.java

Reverts bcgov/EDUC-GRAD-STUDENT-API#798

Revert "Adds endpoint to retrieve graduation counts for school IDs"
